name: 'Docker Push'
description: 'Push images'

inputs:
  target:
    description: "Target to build"
    required: true
  image:
    description: "Image to push"
    required: true
  file:
    description: "Docker file to use"
    required: false
    default: "./docker/Dockerfile"
  push:
    description: Push the built image
    required: false
    default: 'true'
  description:
    description: "Description of the image"
    required: false
  version:
    description: "Version from git"
    required: false

runs:
  using: "composite"
  steps:
    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}},priority=200
          type=semver,pattern={{major}}.{{minor}},priority=300
          type=ref,event=branch,priority=400
          type=sha,priority=500
          type=raw,value=${{ inputs.version }},enabled=${{ inputs.version != null }}
        labels: |
          org.opencontainers.image.title=${{ inputs.image }}
          org.opencontainers.image.description=${{ inputs.description }}
        flavor: |
          latest=${{ github.ref_type == 'tag' }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: ${{ inputs.target }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
