name: 'Docker Push'
description: 'Push images'

inputs:
  target:
    description: "Target to build"
    required: true
  image:
    description: "Image to push"
    required: true
  file:
    description: "Docker file to use"
    required: false
    default: "./docker/Dockerfile"
  push:
    description: Push the built image
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha

    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: ${{ inputs.target }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
