name: Dependabot auto-approve

on:
  pull_request:
    branches: [ "dependabot/**" ]

permissions:
  pull-requests: write
  actions: read
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Approve PR & Request Merge
        run: gh pr review --approve --body "@dependabot squash and merge" "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
