name: Test
on: [pull_request]

jobs:
  test:
    name: ${{ matrix.module }} Tests (Py ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        module: [Api, Core]

    steps:
      - uses: ${{ github.repository }}/.github/workflows/module-pytest.yml@{{ github.sha }}
        with:
          module: ${{ matrix.module }}
          python-version: ${{ matrix.python-version }}
